version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-movies}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
